### ISSUE TITLE
Write to change_history table fails with duplicate PRIMARY KEY entry

### ISSUE THREAD

**Issue by Dundo777** [Middlecon/DBImport#73]
Data types for some columns were changed on source and when dbimport writes that changes in table_change_history it fails due to primary key constraint violation. 
Primary key is composed of: hive_db, hive_table and eventtime. 
Eventime has a granularity of one second, since there were multiple changes, dbimport writes them in less than a second and therefore violates the constraint. 

Maybe column_name could be added to primary key.

ERROR log example:

```
[2020-05-12 16:38:31,807] {bash_operator.py:110} INFO - INFO - Connecting to Hive
[2020-05-12 16:38:31,838] {bash_operator.py:110} INFO - INFO - USE `default`
[2020-05-12 16:38:31,952] {bash_operator.py:110} INFO - INFO - Checking Hive functionality by querying the reference table
[2020-05-12 16:38:31,953] {bash_operator.py:110} INFO - INFO - select id, value, count(value) as counter from dbimport.validate_table group by id, value order by id
[2020-05-12 16:38:32,192] {bash_operator.py:110} INFO - INFO - Updating Import table columns based on source system schema
[2020-05-12 16:38:32,317] {bash_operator.py:110} INFO - INFO - alter table `etl_import_staging`.`test__employee__staging` change column `bonus` `bonus` numeric
[2020-05-12 16:38:32,591] {bash_operator.py:110} INFO - INFO - alter table `etl_import_staging`.`test__employee__staging` change column `comm` `comm` numeric
[2020-05-12 16:38:32,859] {bash_operator.py:110} INFO - 
[2020-05-12 16:38:32,860] {bash_operator.py:110} INFO - 
[2020-05-12 16:38:32,860] {bash_operator.py:110} INFO - 
[2020-05-12 16:38:32,861] {bash_operator.py:110} INFO - Traceback (most recent call last):
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport_env/lib64/python3.6/site-packages/mysql/connector/connection_cext.py", line 472, in cmd_query
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     raw_as_string=raw_as_string)
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO - _mysql_connector.MySQLInterfaceError: Duplicate entry 'etl_import_staging-test__employee__staging-2020-05-12 16:38:' for key 'PRIMARY'
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO - 
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO - During handling of the above exception, another exception occurred:
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO - 
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO - Traceback (most recent call last):
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport/bin/import", line 1469, in <module>
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     main(sys.argv[1:])
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport/bin/import", line 545, in main
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     import_operation.updateExternalImportTable()
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport/bin/DBImportOperation/import_operations.py", line 1045, in updateExternalImportTable
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     self.updateHiveTable(self.import_config.Hive_Import_DB, self.import_config.Hive_Import_Table, sourceIsParquetFile=True)
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport/bin/DBImportOperation/import_operations.py", line 1220, in updateHiveTable
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     self.import_config.logHiveColumnTypeChange(row['name'], columnType=row['type'], previous_columnType=previous_columnType, hiveDB=hiveDB, hiveTable=hiveTable)
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport/bin/DBImportConfig/import_config.py", line 142, in logHiveColumnTypeChange
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     self.common_config.logHiveColumnTypeChange(column, columnType, previous_columnType=previous_columnType, description=description, hiveDB=hiveDB, hiveTable=hiveTable)
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport/bin/DBImportConfig/common_config.py", line 969, in logHiveColumnTypeChange
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     self.mysql_cursor.execute(query, (hiveDB, hiveTable, column, datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'), previous_columnType, columnType, description))
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -   File "/usr/local/dbimport_env/lib64/python3.6/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
[2020-05-12 16:38:32,862] {bash_operator.py:110} INFO -     raw_as_string=self._raw_as_string)
[2020-05-12 16:38:32,863] {bash_operator.py:110} INFO -   File "/usr/local/dbimport_env/lib64/python3.6/site-packages/mysql/connector/connection_cext.py", line 475, in cmd_query
[2020-05-12 16:38:32,863] {bash_operator.py:110} INFO -     sqlstate=exc.sqlstate)
[2020-05-12 16:38:32,863] {bash_operator.py:110} INFO - mysql.connector.errors.IntegrityError: 1062 (23000): Duplicate entry 'etl_import_staging-test__employee__staging-2020-05-12 16:38:' for key 'PRIMARY'
[2020-05-12 16:38:33,016] {bash_operator.py:114} INFO - Command exited with return code 1

**Comment by BerryOsterlund** [comment]
In version 0.64, the primary key was dropped from that table and only the index that consist of the database and table remains. So after an upgrade to a version later that 0.64, this should not be an issue any longer.
