### ISSUE TITLE
DBImport integration with Apache Atlas for Discovery  - user id and password 

### ISSUE THREAD

**Issue by dev01metatech** [Middlecon/DBImport#80]
thank you very much for creating a nice framework.  I do need to specify the apache atlas user id and password for integration and I am not sure what is variable to be placed on dbimport.cfg . I have working atlas on localhost and I am getting follow error message as atlas needs user id and password for integration. 

DEBUG lookupConnectionAlias -     jdbc_logintimeout = None
DEBUG lookupConnectionAlias -     jdbc_password_file = /tmp/dbimport.3585178.tmp/jdbc_passwd
DEBUG lookupConnectionAlias -     jdbc_oracle_sid = None
DEBUG lookupConnectionAlias -     jdbc_oracle_servicename = None
DEBUG lookupConnectionAlias - Executing common_config.lookupConnectionAlias() - Finished
DEBUG checkAtlasSchema - Executing common_config.checkAtlasSchema()
INFO checkAtlasSchema - Checking Atlas connection
DEBUG atlasGetData - Executing common_config.atlasGetData()
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate()
DEBUG _new_conn - Starting new HTTP connection (1): localhost:21000
DEBUG _make_request - http://localhost:21000 "GET /api/atlas/v2/types/typedef/name/DBImport_Process HTTP/1.1" 401 174
DEBUG handle_401 - handle_401(): Handling: 401
DEBUG handle_401 - handle_401(): Kerberos is not supported
DEBUG handle_401 - handle_401(): returning <Response [401]>
DEBUG handle_response - handle_response(): returning <Response [401]>
DEBUG handle_response - handle_response() has seen 0 401 responses
DEBUG handle_401 - handle_401(): Handling: 401
DEBUG handle_401 - handle_401(): Kerberos is not supported
DEBUG handle_401 - handle_401(): returning <Response [401]>
DEBUG handle_response - handle_response(): returning <Response [401]>
DEBUG handle_response - handle_response() has seen 1 401 responses
DEBUG handle_response - handle_response(): returning 401 <Response [401]>
DEBUG atlasCommunicate - Atlas statusCode = 401
DEBUG atlasCommunicate - Atlas data = {
"servlet":"jersey-servlet",
"message":"Full authentication is required to access this resource",
"url":"/api/atlas/v2/types/typedef/name/DBImport_Process",
"status":"401"
}
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate() - Finished
WARNING checkAtlasSchema - Atlas communication failed with response 401

**Comment by BerryOsterlund** [comment]
Hi

Atlas integration is right now hardcoded to use Kerberos authentication. What I could do is to implement the ability to select username/password or Kerberos as authentication method against Atlas. I'll take a look at it and keep you updated.

**Comment by BerryOsterlund** [comment]
The change in order to get username/password authentication against Atlas was fairly simple to implement. The latest version have support for that. You need to add the following settings to your dbimport.cfg file under the [Atlas] section in order to get it to work. 

# Authentication_type have two valid settings. 'username' or 'kerberos'
authentication_type = username
username = <YOUR_USER>
password = <YOUR_PASSWORD>

Please let me know if it works for you.

**Comment by dev01metatech** [comment]
Thanks for looking into. I  added as suggested about on dbimport.cfg for username and password but when I looked the code - it is not looking for these variable. I believe  we need to make a code change to  following  to add  "atlas_user"  and "atlas_password"  on dbimport.cfg and these variable needs to be detected by following code block.

DBImportConfig/common_config.py:                return self.atlasCommunicate(URL=URL, requestType="GET", logger=logger)
DBImportConfig/common_config.py:                return self.atlasCommunicate(URL=URL, requestType="POST", data=data, logger=logger)
DBImportConfig/common_config.py:                return self.atlasCommunicate(URL=URL, requestType="DELETE", logger=logger)
DBImportConfig/common_config.py:        def atlasCommunicate(self, URL, requestType, data=None, logger=""):

may be like following?

  return self.atlasCommunicate(URL=URL, atlas_user= "ATLAS_USER", atlas_password="ATLAS_PASSWORD"  requestType="GET", logger=logger)

**Comment by dev01metatech** [comment]
current configuration  
[Atlas]
# In order to have lineage in Atlas for DBImport, you need to specify the webaddress to Atlas. 
# If you dont want Atlas integration, just specify an empty address.
address = http://localhost:21000
username = admin
password = admin
timeout = 5
ssl_verify = false
#ssl_cert_path = /etc/ssl/certs/ca-bundle.crt

proposed config change dbimport.cfg for [Atlas]

[Atlas]
# In order to have lineage in Atlas for DBImport, you need to specify the webaddress to Atlas. 
# If you dont want Atlas integration, just specify an empty address.
atlas_server_url =  localhost
atlas_server_http_method = https
atlas_server_port = 21000
atlas_server_user = admin
atlas_server_password = admin
timeout = 5
ssl_verify = false
ssl_cert_path = /etc/ssl/certs/ca-bundle.crt

**Comment by dev01metatech** [comment]
I like keep all these user ids and password  on database like what you have it for JDBC_CONNECTION table ; so that it is encrypted and meets enterprise need of non text password on scripts

**Comment by BerryOsterlund** [comment]
I checked the code, and the implementation is there. Did you pull the last commit from the Git repo? It's not in a ready release yet, so you need to pull it from Git. 

Regarding encryption of passwords in the configuration file. Yes, it's not a bad idea. I will add it to my ToDo list. That goes for both Atlas password but also for the password to the configuration database that exists in there. 

I will take a look at the proposed config change for the configuration file. As it's already under the [Atlas] section, the setting is already dedicated to the Atlas config. Thats why I dont include a prefix on each setting. Is there a specific reason to why you want to split up the URL into dedicated settings instead of just having the URL as a complete string?

**Comment by dev01metatech** [comment]
Is there a specific reason to why you want to split up the URL into dedicated settings instead of just having the URL as a complete string?
1. it is for readability & less brain has  to think!!! basically
2. authentication type  atlas authentication is not configured correctly. Valid options are 'username' or 'kerberos'
       - do want to call this as username or basic?  either way is fine?
3. after pulling the new code - user needs to do the following 
      - copy old configuration file  dbimport.cfg 
      - copy .perm key from old conf directory new 
      -  edit  dbimport.cfg   - add atlas configuration information 
4. it looks like able to connect to the atlas - I need to run the setup  - I will keep you posted 

      ./manage -v --discoverAtlasRdbms -a e2eadmin_mysql
DEBUG lookupConnectionAlias -     jdbc_oracle_servicename = None
DEBUG lookupConnectionAlias - Executing common_config.lookupConnectionAlias() - Finished
DEBUG checkAtlasSchema - Executing common_config.checkAtlasSchema()
INFO checkAtlasSchema - Checking Atlas connection
DEBUG atlasGetData - Executing common_config.atlasGetData()
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate()
DEBUG _new_conn - Starting new HTTP connection (1): localhost:21000
DEBUG _make_request - http://localhost:21000 "GET /api/atlas/v2/types/typedef/name/DBImport_Process HTTP/1.1" 404 None
DEBUG atlasCommunicate - Atlas statusCode = 404
DEBUG atlasCommunicate - Atlas data = {"errorCode":"ATLAS-404-00-001","errorMessage":"Given typename DBImport_Process was invalid"}
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate() - Finished
WARNING checkAtlasSchema - The Atlas typeDef 'DBImport_Process' was not found. Did you run the Atlas setup for DBImport?

**Comment by dev01metatech** [comment]
I get the following and atlas is integrated with opendistro ELK not using solr 

./manage -v --discoverAtlasRdbms -a e2eadmin_mysql

DEBUG updateAtlasWithRDBMSdata - ======================================
DEBUG atlasPostData - Executing common_config.atlasPostData()
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate()
DEBUG _new_conn - Starting new HTTP connection (1): localhost:21000
ERROR atlasCommunicate - RequestException error when communicating with Atlas on http://localhost:21000/api/atlas/v2/entity/bulk
WARNING atlasCommunicate - Atlas integration is Disabled
DEBUG atlasCommunicate - Atlas data: {"referredEntities": {"-100": {"guid": "-100", "typeName": "rdbms_table", "attributes": {"qualifiedName": "DBImport.table_change_history@e2eadmin2:3306", "name": "table_change_history", "name_path": null, "contact_info": "", "owner": "", "comment": "This table keeps track of all changes that was done to an abject after the initial load. Example could be that a colum type was changed from char(10) to varchar(10). That kind of information is logged in this table", "type": "table", "createTime": "2020-11-15T11:35:15.000Z", "db": {"guid": "-300", "typeName": "rdbms_db"}}}, "-300": {"guid": "-300", "typeName": "rdbms_db", "attributes": {"qualifiedName": "DBImport@e2eadmin2:3306", "name": "DBImport", "contact_info": "", "owner": "", "description": "", "prodOrOther": "Unspecified", "instance": {"guid": "-400", "typeName": "rdbms_instance"}}}, "-400": {"guid": "-400", "typeName": "rdbms_instance", "attributes": {"qualifiedName": "MySQL@e2eadmin2:3306", "name": "MySQL", "rdbms_type": "MySQL", "hostname": "e2eadmin2", "port": "3306", "platform": "", "protocol": "jdbc"}}}, "entities": [{"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.hive_db@e2eadmin2:3306", "owner": "", "comment": "Hive Database", "length": "128", "name": "hive_db", "data_type": "varchar(128)", "isNullable": false, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.hive_table@e2eadmin2:3306", "owner": "", "comment": "Hive Table", "length": "128", "name": "hive_table", "data_type": "varchar(128)", "isNullable": false, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.column_name@e2eadmin2:3306", "owner": "", "comment": "Column Name", "length": "128", "name": "column_name", "data_type": "varchar(128)", "isNullable": false, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.eventtime@e2eadmin2:3306", "owner": "", "comment": "Time and date of the event", "name": "eventtime", "data_type": "datetime", "isNullable": false, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.event@e2eadmin2:3306", "owner": "", "comment": "Event name.", "length": "128", "name": "event", "data_type": "varchar(128)", "isNullable": false, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.previous_value@e2eadmin2:3306", "owner": "", "comment": "Value before the change", "length": "128", "name": "previous_value", "data_type": "varchar(128)", "isNullable": true, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.value@e2eadmin2:3306", "owner": "", "comment": "Value after the change", "length": "128", "name": "value", "data_type": "varchar(128)", "isNullable": true, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}, {"typeName": "rdbms_column", "createdBy": "DBImport", "attributes": {"qualifiedName": "DBImport.table_change_history.description@e2eadmin2:3306", "owner": "", "comment": "Detailed description of the event", "length": "512", "name": "description", "data_type": "varchar(512)", "isNullable": false, "isPrimaryKey": false, "table": {"guid": "-100", "typeName": "rdbms_table"}}}]}
DEBUG atlasCommunicate - Atlas requestType: POST
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate() - Finished
DEBUG remove_temporary_files - Executing common_config.remove_temporary_files()
DEBUG remove_temporary_files - Executing common_config.remove_temporary_files() - Finished
Traceback (most recent call last):
  File "./manage", line 854, in <module>
    main(sys.argv[1:])
  File "./manage", line 486, in main
    commonConfig.discoverAtlasRdbms(connectionAlias)
  File "/metatech/dbimport/DBImport/bin/DBImportConfig/common_config.py", line 2457, in discoverAtlasRdbms
    dbUri = returnDict["dbUri"]
TypeError: 'NoneType' object is not subscriptable

**Comment by dev01metatech** [comment]
I looked at the atlas and it looks like it is added &  discovered tables and columns but not sure why it  gave the error above. 
![altas_dbimports_jdbc_connections](https://user-images.githubusercontent.com/72705041/99508115-3cdb6380-2952-11eb-9b47-acfa6a4a6877.png)

**Comment by dev01metatech** [comment]
I was able to reproduce the error by adding new table and trying to discover. 
1. add new table to the database 
2. run discovery command 
3. error you get  ( strange is it is able to discover the table on atlas but giving the error message)

DEBUG atlasCommunicate - Atlas requestType: POST
DEBUG atlasCommunicate - Executing common_config.atlasCommunicate() - Finished
DEBUG remove_temporary_files - Executing common_config.remove_temporary_files()
DEBUG remove_temporary_files - Executing common_config.remove_temporary_files() - Finished
Traceback (most recent call last):
  File "./manage", line 854, in <module>
    main(sys.argv[1:])
  File "./manage", line 486, in main
    commonConfig.discoverAtlasRdbms(connectionAlias)
  File "/metatech/dbimport/DBImport/bin/DBImportConfig/common_config.py", line 2457, in discoverAtlasRdbms
    dbUri = returnDict["dbUri"]
TypeError: 'NoneType' object is not subscriptable
