### ISSUE TITLE
python3.8  AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by dev01metatech** [Middlecon/DBImport#83]
pip3 uninstall PyCrypto
pip3 install -U PyCryptodome

do above fix the below problem 

Traceback (most recent call last):
  File "./manage", line 854, in <module>
    main(sys.argv[1:])
  File "./manage", line 585, in main
    commonConfig.encryptUserPassword(connectionAlias, username, password)
  File "/metatech/DBImport/bin/DBImportConfig/common_config.py", line 1056, in encryptUserPassword
    encryptedStr = self.crypto.encrypt(strToEncrypt)
  File "/metatech/DBImport/bin/DBImportConfig/decryption.py", line 85, in encrypt
    strEncrypted = cipher.encrypt(strToEncrypt.encode())
  File "/metatech/dbimport/venv/lib/python3.8/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 135, in encrypt
    ps = tobytes(list(map(nonZeroRandByte(randFunc), randFunc(k-mLen-3))))
  File "/metatech/dbimport/venv/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/metatech/dbimport/venv/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/metatech/dbimport/venv/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/metatech/dbimport/venv/lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
AttributeError: module 'time' has no attribute 'clock'

**Comment by dev01metatech** [comment]
above did not solve it - so i have to make modification on below file - it will impact on future python package updates 
lib/python3.8/site-packages/Crypto/Random/_UserFriendlyRNG.py

 #t = time.clock()
        t = time.perf_counter()

**Comment by dev01metatech** [comment]
above needs to be fixed with   PyCryptodome package
